#!/bin/bash

d="$(dirname $0)"

echo "Pulling code..."
cd $d/..
git pull

#virtualenv startup
source desio/bin/activate

echo "Migrating..."
cd desio/model
python migrations/manage.py upgrade production.ini

echo "Restarting pylons..."
cd ../../
deploy/paster restart

cd -