#!/bin/sh -e

d="/home/ubuntu/binder"

case "$1" in
  start)
    paster serve --daemon --pid-file=$d/paster.pid --log-file=$d/paster.log $d/Desio/production.ini start
    ;;
  stop)
    paster serve --daemon --pid-file=$d/paster.pid --log-file=$d/paster.log  $d/Desio/production.ini stop
    ;;
  restart)
    paster serve  --daemon --pid-file=$d/paster.pid --log-file=$d/paster.log $d/Desio/production.ini restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac